language: bash
dist: bionic
before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
script:
  - docker buildx version
  - export multiarch="linux/amd64 linux/arm64 linux/ppc64le linux/s390x linux/386 linux/arm/v7 linux/arm/v6"
  - echo ${multiarch}
  - for arch in ${multiarch}; do docker buildx build --platform ${arch} --tag alpine/ansible --load . ; done
  - docker images |grep ansible
  - docker run -ti --rm ansible/ansible ansible --version
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - for arch in ${multiarch}; do echo ${arch}; docker buildx build --platform ${arch} --tag alpine/ansible --push . ; done
